// @ts-check
// Auto-generate the grammars sidebar from the per-book folders included by the
// docs plugin (each book folder becomes a category, its .mdx the entries).

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  grammarsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
