// AUTO-GENERATED by scripts/build_sandhi_frequency.py — do not hand-edit.
// Source: kosha data/sandhi/corpus_sandhi.tsv (17 texts; sandhi programme).
// Vowel-coalescence junctions only — the family SandhiCollider models.
// Keyed by "<left> <right>" input pair; `rank` is the junction's position
// among all 9840 corpus sandhi rules by frequency (1 = most common).
export const TOTAL_SANDHI_RULES = 9840;
export const SANDHI_FREQ = {
  "a a": {
    "count": 35533,
    "example": "ajara+amara→ajarāmaravat",
    "nTexts": 17,
    "out": "ā",
    "pct": 6.12,
    "rank": 1
  },
  "a e": {
    "count": 8694,
    "example": "na+eva→naivābhigamanaṃ",
    "nTexts": 17,
    "out": "ai",
    "pct": 1.5,
    "rank": 14
  },
  "a i": {
    "count": 5375,
    "example": "ajāgalastanasya+iva→ajāgalastanasyeva",
    "nTexts": 16,
    "out": "e",
    "pct": 0.93,
    "rank": 27
  },
  "a o": {
    "count": 562,
    "example": "sarva+oṣadhi→sarvauṣadhirasenābhiṣiktaḥ",
    "nTexts": 11,
    "out": "au",
    "pct": 0.1,
    "rank": 141
  },
  "a u": {
    "count": 7777,
    "example": "saṃskṛta+uktiṣu→saṃskṛtoktiṣu",
    "nTexts": 17,
    "out": "o",
    "pct": 1.34,
    "rank": 16
  },
  "a ā": {
    "count": 12488,
    "example": "ākarṇya+ātmanaḥ→ākarṇyātmanaḥ",
    "nTexts": 17,
    "out": "ā",
    "pct": 2.15,
    "rank": 10
  },
  "a ī": {
    "count": 821,
    "example": "prayaccha+īśvare→prayaccheśvare",
    "nTexts": 16,
    "out": "e",
    "pct": 0.14,
    "rank": 117
  },
  "a ū": {
    "count": 214,
    "example": "artha+ūṣmaṇā→arthoṣmaṇā",
    "nTexts": 13,
    "out": "o",
    "pct": 0.04,
    "rank": 200
  },
  "a ṛ": {
    "count": 1350,
    "example": "tasya+ṛṣeḥ→tasyarṣeḥ",
    "nTexts": 7,
    "out": "ar",
    "pct": 0.23,
    "rank": 90
  },
  "ai a": {
    "count": 4,
    "example": "",
    "nTexts": 2,
    "out": "ā a",
    "pct": 0.0,
    "rank": 1457
  },
  "ai e": {
    "count": 2,
    "example": "tasmā+eva",
    "nTexts": 2,
    "out": "ā e",
    "pct": 0.0,
    "rank": 2312
  },
  "ai i": {
    "count": 2,
    "example": "anyasmā+iti",
    "nTexts": 1,
    "out": "ā i",
    "pct": 0.0,
    "rank": 3241
  },
  "ai u": {
    "count": 1,
    "example": "",
    "nTexts": 1,
    "out": "ā u",
    "pct": 0.0,
    "rank": 7428
  },
  "ai ā": {
    "count": 2,
    "example": "tasmā+ācacakṣe",
    "nTexts": 1,
    "out": "ā ā",
    "pct": 0.0,
    "rank": 3276
  },
  "ai ṛ": {
    "count": 1,
    "example": "vā+ṛtu",
    "nTexts": 1,
    "out": "ā ṛ",
    "pct": 0.0,
    "rank": 6250
  },
  "au a": {
    "count": 213,
    "example": "ādyāv+antimas",
    "nTexts": 7,
    "out": "āv a",
    "pct": 0.04,
    "rank": 201
  },
  "au e": {
    "count": 39,
    "example": "ādāv+eva",
    "nTexts": 8,
    "out": "āv e",
    "pct": 0.01,
    "rank": 383
  },
  "au i": {
    "count": 97,
    "example": "ravāv+iva",
    "nTexts": 8,
    "out": "āv i",
    "pct": 0.02,
    "rank": 262
  },
  "au o": {
    "count": 2,
    "example": "taṭāv+ogha",
    "nTexts": 2,
    "out": "āv o",
    "pct": 0.0,
    "rank": 2326
  },
  "au u": {
    "count": 96,
    "example": "pādāv+upatiṣṭhate",
    "nTexts": 7,
    "out": "āv u",
    "pct": 0.02,
    "rank": 264
  },
  "au ā": {
    "count": 34,
    "example": "stanāv+ā",
    "nTexts": 8,
    "out": "āv ā",
    "pct": 0.01,
    "rank": 412
  },
  "au ū": {
    "count": 5,
    "example": "tāv+ūcatuḥ",
    "nTexts": 2,
    "out": "āv ū",
    "pct": 0.0,
    "rank": 1210
  },
  "au ṛ": {
    "count": 26,
    "example": "tāv+ṛṣyamūkaṃ",
    "nTexts": 2,
    "out": "āv ṛ",
    "pct": 0.0,
    "rank": 468
  },
  "e a": {
    "count": 2523,
    "example": "dantake+'vasthāpya",
    "nTexts": 15,
    "out": "e '",
    "pct": 0.43,
    "rank": 51
  },
  "e e": {
    "count": 401,
    "example": "sarva+eva",
    "nTexts": 12,
    "out": "a e",
    "pct": 0.07,
    "rank": 161
  },
  "e i": {
    "count": 266,
    "example": "prapadyata+iti",
    "nTexts": 14,
    "out": "a i",
    "pct": 0.05,
    "rank": 183
  },
  "e o": {
    "count": 1,
    "example": "anta+ojasvinām",
    "nTexts": 1,
    "out": "a o",
    "pct": 0.0,
    "rank": 5052
  },
  "e u": {
    "count": 108,
    "example": "citragrīva+uvāca",
    "nTexts": 8,
    "out": "a u",
    "pct": 0.02,
    "rank": 253
  },
  "e ā": {
    "count": 98,
    "example": "te+ātma→tavātmajñasya",
    "nTexts": 6,
    "out": "av ā",
    "pct": 0.02,
    "rank": 261
  },
  "e ī": {
    "count": 12,
    "example": "te+īhitam→tavehitaṃ",
    "nTexts": 5,
    "out": "ave",
    "pct": 0.0,
    "rank": 707
  },
  "e ū": {
    "count": 9,
    "example": "sarva+ūcur",
    "nTexts": 1,
    "out": "a ū",
    "pct": 0.0,
    "rank": 863
  },
  "e ṛ": {
    "count": 1,
    "example": "mahīpāla+ṛṣyaśṛṅgaṃ",
    "nTexts": 1,
    "out": "a ṛ",
    "pct": 0.0,
    "rank": 5081
  },
  "i a": {
    "count": 6679,
    "example": "iti+anujñātaḥ→ityanujñātaḥ",
    "nTexts": 17,
    "out": "y a",
    "pct": 1.15,
    "rank": 21
  },
  "i e": {
    "count": 2386,
    "example": "iti+evam→ityevaṃ",
    "nTexts": 15,
    "out": "y e",
    "pct": 0.41,
    "rank": 53
  },
  "i i": {
    "count": 1691,
    "example": "khādati+iti→khādatīti",
    "nTexts": 15,
    "out": "ī",
    "pct": 0.29,
    "rank": 74
  },
  "i o": {
    "count": 21,
    "example": "romāṇi+oṣadhayaḥ→romāṇyoṣadhayas",
    "nTexts": 3,
    "out": "y o",
    "pct": 0.0,
    "rank": 516
  },
  "i u": {
    "count": 2095,
    "example": "bhavati+uttarasādhakaḥ→bhavatyuttarasādhakaḥ",
    "nTexts": 16,
    "out": "y u",
    "pct": 0.36,
    "rank": 61
  },
  "i ā": {
    "count": 1223,
    "example": "sarvāṇi+ānaya→sarvāṇyānaya",
    "nTexts": 16,
    "out": "y ā",
    "pct": 0.21,
    "rank": 96
  },
  "i ī": {
    "count": 105,
    "example": "bhavati+īśvarāṇām→bhavatīśvarāṇāṃ",
    "nTexts": 9,
    "out": "ī",
    "pct": 0.02,
    "rank": 255
  },
  "i ū": {
    "count": 46,
    "example": "iti+ūcuḥ→ityūcus",
    "nTexts": 9,
    "out": "y ū",
    "pct": 0.01,
    "rank": 365
  },
  "i ṛ": {
    "count": 49,
    "example": "phalanti+ṛtuṣu→phalantyṛtuṣu",
    "nTexts": 2,
    "out": "y ṛ",
    "pct": 0.01,
    "rank": 354
  },
  "o a": {
    "count": 14,
    "example": "aho+'smi",
    "nTexts": 2,
    "out": "o '",
    "pct": 0.0,
    "rank": 666
  },
  "o i": {
    "count": 1,
    "example": "naur+iva",
    "nTexts": 1,
    "out": "ur i",
    "pct": 0.0,
    "rank": 7284
  },
  "o ā": {
    "count": 6,
    "example": "go+ākṛtīn→gavākṛtīn",
    "nTexts": 2,
    "out": "av ā",
    "pct": 0.0,
    "rank": 1083
  },
  "u a": {
    "count": 2244,
    "example": "sādhu+asādhu→sādhvasādhvapi",
    "nTexts": 15,
    "out": "v a",
    "pct": 0.39,
    "rank": 57
  },
  "u e": {
    "count": 467,
    "example": "nanu+etat→nanvetan",
    "nTexts": 11,
    "out": "v e",
    "pct": 0.08,
    "rank": 148
  },
  "u i": {
    "count": 567,
    "example": "bhavatu+iti→bhavatviti",
    "nTexts": 11,
    "out": "v i",
    "pct": 0.1,
    "rank": 140
  },
  "u o": {
    "count": 1,
    "example": "apatyeṣv+oghena",
    "nTexts": 1,
    "out": "v o",
    "pct": 0.0,
    "rank": 3993
  },
  "u u": {
    "count": 226,
    "example": "dhīvareṣu+upasthiteṣu→dhīvareṣūpasthiteṣu",
    "nTexts": 13,
    "out": "ū",
    "pct": 0.04,
    "rank": 196
  },
  "u ā": {
    "count": 381,
    "example": "tu+ātmānam→tvātmānameveha",
    "nTexts": 13,
    "out": "v ā",
    "pct": 0.07,
    "rank": 164
  },
  "u ī": {
    "count": 10,
    "example": "yugeṣu+īṣāsu→yugeṣvīṣāsu",
    "nTexts": 3,
    "out": "v ī",
    "pct": 0.0,
    "rank": 784
  },
  "u ū": {
    "count": 7,
    "example": "bāhu+ūru→bāhūruvegaṃ",
    "nTexts": 2,
    "out": "ū",
    "pct": 0.0,
    "rank": 1036
  },
  "u ṛ": {
    "count": 15,
    "example": "vyāharatsu+ṛṣi→vyāharatsvṛṣiputreṣu",
    "nTexts": 2,
    "out": "v ṛ",
    "pct": 0.0,
    "rank": 634
  },
  "ā a": {
    "count": 7786,
    "example": "nīcagā+api→nīcagāpi",
    "nTexts": 17,
    "out": "ā",
    "pct": 1.34,
    "rank": 15
  },
  "ā e": {
    "count": 3063,
    "example": "vidyā+eva→vidyaiva",
    "nTexts": 15,
    "out": "ai",
    "pct": 0.53,
    "rank": 43
  },
  "ā i": {
    "count": 2730,
    "example": "vā+iti→veti",
    "nTexts": 15,
    "out": "e",
    "pct": 0.47,
    "rank": 48
  },
  "ā o": {
    "count": 130,
    "example": "mahā+ojasaḥ→mahaujasaḥ",
    "nTexts": 6,
    "out": "au",
    "pct": 0.02,
    "rank": 238
  },
  "ā u": {
    "count": 1519,
    "example": "rājā+uvāca→rājovāca",
    "nTexts": 16,
    "out": "o",
    "pct": 0.26,
    "rank": 86
  },
  "ā ā": {
    "count": 1695,
    "example": "dvitīyā+ādriyate→dvitīyādriyate",
    "nTexts": 17,
    "out": "ā",
    "pct": 0.29,
    "rank": 73
  },
  "ā ī": {
    "count": 92,
    "example": "yathā+īpsitam→yathepsitam",
    "nTexts": 7,
    "out": "e",
    "pct": 0.02,
    "rank": 271
  },
  "ā ū": {
    "count": 50,
    "example": "dayā+ūrmiḥ→dayormiḥ",
    "nTexts": 7,
    "out": "o",
    "pct": 0.01,
    "rank": 346
  },
  "ā ṛ": {
    "count": 611,
    "example": "mahā+ṛṣeḥ→maharṣes",
    "nTexts": 9,
    "out": "ar",
    "pct": 0.11,
    "rank": 135
  },
  "ī a": {
    "count": 205,
    "example": "padminī+api→padminyapi",
    "nTexts": 11,
    "out": "y a",
    "pct": 0.04,
    "rank": 208
  },
  "ī e": {
    "count": 31,
    "example": "sarasvatī+evam→sarasvatyevamabravīt",
    "nTexts": 6,
    "out": "y e",
    "pct": 0.01,
    "rank": 428
  },
  "ī i": {
    "count": 313,
    "example": "svāmī+iti→svāmīti",
    "nTexts": 14,
    "out": "ī",
    "pct": 0.05,
    "rank": 172
  },
  "ī o": {
    "count": 1,
    "example": "nadī+oghān→nadyoghān",
    "nTexts": 1,
    "out": "y o",
    "pct": 0.0,
    "rank": 5348
  },
  "ī u": {
    "count": 247,
    "example": "bhagavatī+upahāra→bhagavatyupahāratve",
    "nTexts": 5,
    "out": "y u",
    "pct": 0.04,
    "rank": 190
  },
  "ī ā": {
    "count": 49,
    "example": "gantrī+ārohaṇam→gantryārohaṇaṃ",
    "nTexts": 9,
    "out": "y ā",
    "pct": 0.01,
    "rank": 351
  },
  "ī ī": {
    "count": 11,
    "example": "purī+īdṛśī→purīdṛśī",
    "nTexts": 5,
    "out": "ī",
    "pct": 0.0,
    "rank": 753
  },
  "ū i": {
    "count": 1,
    "example": "amū+iti→amūnīty",
    "nTexts": 1,
    "out": "ūnī",
    "pct": 0.0,
    "rank": 4268
  },
  "ū u": {
    "count": 1,
    "example": "vadhū+utsārita→vadhūtsāritahomalājāḥ",
    "nTexts": 1,
    "out": "ū",
    "pct": 0.0,
    "rank": 3913
  },
  "ṛ a": {
    "count": 7,
    "example": "pitṛ+arjitam→pitrarjitaṃ",
    "nTexts": 4,
    "out": "r a",
    "pct": 0.0,
    "rank": 966
  },
  "ṛ e": {
    "count": 3,
    "example": "dhātṛ+eva→dhātreva",
    "nTexts": 2,
    "out": "r e",
    "pct": 0.0,
    "rank": 1720
  },
  "ṛ ā": {
    "count": 1,
    "example": "goptṛ+ātmane→goptrātmane",
    "nTexts": 1,
    "out": "r ā",
    "pct": 0.0,
    "rank": 8619
  }
};
