"""Tests for scripts/toc_build_pages.py (H1839).

Pure helpers + --check drift gate against the committed C2 registry.
"""
import toc_build_pages as tbp


def test_sec_label():
    assert tbp.sec_label("whitney-sec:274") == "§274"
    assert tbp.sec_label("whitney-sec:100-105") == "§100–105"


def test_mermaid_id():
    assert tbp.mermaid_id("SG-MO-001") == "SG_MO_001"


def test_short_truncates():
    assert tbp.short("short") == "short"
    long = "x" * 40
    out = tbp.short(long, n=10)
    assert len(out) == 10
    assert out.endswith("…")


def test_chapter_of_maps_anchor():
    chapters = {
        "3": {"sections": "200-300"},
        "4": {"sections": "301-400"},
    }
    assert tbp.chapter_of("whitney-sec:274", chapters) == "3"
    assert tbp.chapter_of("whitney-sec:350", chapters) == "4"
    assert tbp.chapter_of("whitney-sec:9999", chapters) == ""


def test_load_registry_and_coverage():
    reg, cov = tbp.load()
    assert "articles" in reg and "domains" in reg
    assert len(reg["articles"]) >= 1
    assert "chapters" in cov


def test_build_overview_contains_domain_table():
    reg, cov = tbp.load()
    body = tbp.build_overview(reg, cov)
    assert "AUTO-GENERATED by scripts/toc_build_pages.py" in body
    assert "| Домен | Код | Статей |" in body
    assert "flowchart LR" in body


def test_check_mode_pages_in_sync():
    """Committed generated pages must match a fresh build (--check exit 0)."""
    import sys
    old = sys.argv[:]
    try:
        sys.argv = ["toc_build_pages.py", "--check"]
        rc = tbp.main()
    finally:
        sys.argv = old
    assert rc == 0, "toc pages out of sync — run: python scripts/toc_build_pages.py"
