#!/usr/bin/env python
"""Generate PARSE_AUDIT.md from parse_audit.yml (KnauerFrazy_1908).

Sibling of scripts/build_claims.py, same hand-edited-source + generated-output pattern:
`parse_audit.yml` is the structured source; `PARSE_AUDIT.md` is generated — never edit it by
hand. Built when the register scaled from the 10-entry seed to the full footnote drain
(H797 scope fork; the seed's header anticipated exactly this).

Usage:  python KnauerFrazy_1908/build_parse_audit.py
"""
import sys, datetime
from pathlib import Path

import yaml

sys.stdout.reconfigure(encoding="utf-8")
sys.stderr.reconfigure(encoding="utf-8")

HERE = Path(__file__).resolve().parent
BADGE = {"CONFIRMED": "✅ CONFIRMED", "QUESTIONABLE": "🟡 QUESTIONABLE", "ERROR": "❌ ERROR"}


def cell(s):
    return (str(s) if s is not None else "").replace("|", "\\|").replace("\n", " ").strip()


def main():
    data = yaml.safe_load((HERE / "parse_audit.yml").read_text(encoding="utf-8"))
    entries = data.get("entries", []) or []
    synthesis = (data.get("synthesis") or "").strip()
    today = datetime.date.today().strftime("%d-%m-%Y")
    n = len(entries)
    tally = {}
    for e in entries:
        tally[e.get("verdict")] = tally.get(e.get("verdict"), 0) + 1
    parts = [
        "# Parse audit — Knauer, Фразы (1908)",
        "",
        "_Auto-generated from [`parse_audit.yml`](parse_audit.yml) by "
        "[`build_parse_audit.py`](build_parse_audit.py). Do not edit this file by hand — edit "
        "`parse_audit.yml` and re-run the generator._",
        "",
        f"_Generated: {today} · {n} audited parses · "
        + " · ".join(f"{BADGE.get(k, k)} {v}" for k, v in sorted(tally.items())) + "_",
        "",
        "Each entry audits ONE footnote's morphological parse (root + category analysis of a "
        "surface form) for linguistic correctness against Whitney 1889 — not the two-axis "
        "discursive-claim pipeline of `claims.yml` registers; see the methodology in "
        "[`parse_audit.yml`](parse_audit.yml)'s header (H797 scope fork).",
        "",
        "| ID | Location | Form | Claimed parse | Kind | Verdict | Ref |",
        "|--|--|--|--|--|--|--|",
    ]
    for e in entries:
        parts.append(
            f"| **{cell(e.get('id'))}** | {cell(e.get('loc'))} | {cell(e.get('surface_form'))} | "
            f"{cell(e.get('claimed_parse_ru'))} | {cell(e.get('kind'))} | "
            f"{BADGE.get(e.get('verdict'), cell(e.get('verdict')))} | {cell(e.get('ref'))} |")
    if synthesis:
        parts += ["", "## Synthesis", ""]
        for para in synthesis.split("\n\n"):
            para = " ".join(para.split())
            if para:
                parts += [para, ""]
    notes = [(e.get("id"), e.get("evidence")) for e in entries if e.get("evidence")]
    if notes:
        parts += ["", "## Evidence notes", ""]
        for cid, ev in notes:
            parts.append(f"- **{cell(cid)}** — {cell(ev)}")
    parts += ["", f"_Auto-generated by [`build_parse_audit.py`](build_parse_audit.py) on {today}._", ""]
    (HERE / "PARSE_AUDIT.md").write_text("\n".join(parts), encoding="utf-8")
    print(f"PARSE_AUDIT.md: {n} entries, tally {tally}")


if __name__ == "__main__":
    main()
