// <ApteClaims/> — reading-site overlay for the ApteSyntax_1885 claim register.
//
// Renders the two-axis verification of Apte's Guide to Sanskrit Composition (1885, Likhushina
// Russian tr. 2021): every registered assertion with a FACT badge (TRUE / OVERSTATED / FALSE /
// UNTESTABLE) + the corpus/reference number, and a PEDAGOGY badge (is the presentation
// defensible). Data comes from ApteSyntax_1885/claims.json, generated by scripts/build_claims.py
// from claims.yml — never hand-edit the JSON.
//
// Embed on any page:  import ApteClaims from '@site/src/components/ApteClaims';
//                     <ApteClaims/>                       (whole register + tally)
//                     <ApteClaims only="APT-20,APT-31"/>  (badge specific claims)
//                     <ApteClaims filter="FALSE,OVERSTATED"/>  (only the flagged ones)
//
// Verdicts come from three method-controlled corpus instruments (treebank position/agreement;
// Classical-corpus government by baseline lift; pada by present-ending) plus two Whitney
// reference passes — see the book README. Rights: the 1885 English is public domain; the
// overlay carries only *our* verification metadata (verdicts, numbers) and quotes each rule
// minimally, not a re-release of the Likhushina translation.
import React from 'react';
import data from '@site/ApteSyntax_1885/claims.json';

const FACT = {
  TRUE:       {label: 'TRUE',       bg: '#1f7a3d', fg: '#fff'},
  OVERSTATED: {label: 'OVERSTATED', bg: '#b26a00', fg: '#fff'},
  FALSE:      {label: 'FALSE',      bg: '#a11', fg: '#fff'},
  UNTESTABLE: {label: 'UNTESTABLE', bg: 'var(--ifm-color-emphasis-400)', fg: 'var(--ifm-font-color-base)'},
};
const PED = {
  JUSTIFIED:            'justified',
  MISLEADING:           'misleading',
  'RARE-AS-CENTRAL':    'rare-as-central',
  'FREQUENCY-HIDDEN':   'frequency-hidden',
  'ORDER-QUESTIONABLE': 'order-questionable',
};
const PED_OK = k => k === 'JUSTIFIED';
const FACT_ORDER = ['TRUE', 'OVERSTATED', 'FALSE', 'UNTESTABLE'];

function FactBadge({verdict}) {
  const f = FACT[verdict] || {label: verdict || '—', bg: 'var(--ifm-color-emphasis-300)', fg: 'inherit'};
  return (
    <span style={{
      display: 'inline-block', padding: '0.05em 0.5em', borderRadius: '0.5em',
      fontSize: '0.8em', fontWeight: 600, background: f.bg, color: f.fg, whiteSpace: 'nowrap',
    }}>{f.label}</span>
  );
}

function PedBadge({verdict}) {
  if (!verdict) return null;
  const ok = PED_OK(verdict);
  return (
    <span style={{
      display: 'inline-block', padding: '0.05em 0.5em', borderRadius: '0.5em',
      fontSize: '0.8em', border: `1px solid ${ok ? '#1f7a3d' : '#b26a00'}`,
      color: ok ? '#1f7a3d' : '#b26a00', whiteSpace: 'nowrap',
    }}>{PED[verdict] || verdict.toLowerCase()}</span>
  );
}

function Tally({claims}) {
  const counts = FACT_ORDER.map(v => [v, claims.filter(c => c.verdict_fact === v).length]).filter(([, n]) => n);
  return (
    <div style={{display: 'flex', gap: '0.5em', flexWrap: 'wrap', marginBottom: '0.6em'}}>
      {counts.map(([v, n]) => (
        <span key={v} style={{display: 'flex', gap: '0.35em', alignItems: 'center'}}>
          <FactBadge verdict={v} /><strong style={{fontSize: '0.85em'}}>{n}</strong>
        </span>
      ))}
    </div>
  );
}

export default function ApteClaims({only, filter}) {
  const wanted = only ? new Set(only.split(',').map(s => s.trim())) : null;
  const facts = filter ? new Set(filter.split(',').map(s => s.trim().toUpperCase())) : null;
  const claims = data.claims.filter(
    c => (!wanted || wanted.has(c.id)) && (!facts || facts.has(c.verdict_fact)));

  return (
    <div style={{
      border: '1px solid var(--ifm-color-emphasis-300)', borderRadius: '0.6em',
      padding: '1em', margin: '1em 0', background: 'var(--ifm-background-surface-color)',
    }}>
      <div style={{fontSize: '0.85em', color: 'var(--ifm-color-emphasis-700)', marginBottom: '0.6em'}}>
        Проверка утверждений по корпусу DCS-2021 + Уитни 1889 · три корпусных инструмента
        (treebank · classical-government · pada) + два справочных прохода по Уитни ·
        сгенерировано {data.generated} · источник <code>claims.yml</code> (H1055–H1087)
      </div>
      {!only && <Tally claims={data.claims} />}
      {claims.map(c => (
        <div key={c.id} style={{
          padding: '0.6em 0', borderTop: '1px solid var(--ifm-color-emphasis-200)',
        }}>
          <div style={{display: 'flex', gap: '0.5em', alignItems: 'center', flexWrap: 'wrap'}}>
            <strong>{c.id}</strong>
            <FactBadge verdict={c.verdict_fact} />
            <PedBadge verdict={c.verdict_pedagogy} />
            <span style={{fontSize: '0.8em', color: 'var(--ifm-color-emphasis-600)'}}>{c.loc} · {c.kind}</span>
          </div>
          {c.claim_ru && (
            <div style={{fontSize: '0.92em', margin: '0.35em 0', fontStyle: 'italic'}}>«{c.claim_ru}»</div>
          )}
          {c.number && (
            <div style={{fontSize: '0.85em', color: 'var(--ifm-color-emphasis-800)'}}>
              <strong>Проверка:</strong> {c.number}
            </div>
          )}
          {c.note && (
            <details style={{fontSize: '0.85em', margin: '0.3em 0 0'}}>
              <summary style={{cursor: 'pointer', color: 'var(--ifm-color-emphasis-600)'}}>разбор</summary>
              <div style={{
                margin: '0.3em 0 0', padding: '0.3em 0.6em',
                borderLeft: '3px solid var(--ifm-color-primary)',
                background: 'var(--ifm-color-emphasis-100)',
              }}>{c.note}</div>
            </details>
          )}
          {c.ref && (
            <div style={{fontSize: '0.8em', color: 'var(--ifm-color-emphasis-600)', marginTop: '0.3em'}}>{c.ref}</div>
          )}
        </div>
      ))}
    </div>
  );
}
