// <KocherginaClaims/> — reading-site overlay for the H768 claim register.
//
// Renders the two-axis verification of Kochergina's Учебник санскрита (1998): every
// registered assertion with a FACT badge (TRUE / OVERSTATED / FALSE / UNTESTABLE) + the
// corpus number, and a PEDAGOGY badge (is the presentation defensible). Data comes from
// KocherginaUchebnik_1998/claims.json, generated by scripts/build_claims.py from claims.yml
// — never hand-edit the JSON.
//
// Embed on any page:  import KocherginaClaims from '@site/src/components/KocherginaClaims';
//                     <KocherginaClaims/>            (whole register)
//                     <KocherginaClaims only="HK-4a,HK-4b"/>   (badge a specific spot)
//
// Rights: Kochergina 1998 is in-copyright; the overlay badges *our* verification metadata over
// the reading site only (the 06-07-2026 publish override) — it is not a text re-release.
import React from 'react';
import data from '@site/KocherginaUchebnik_1998/claims.json';

const FACT = {
  TRUE:       {label: 'TRUE',       bg: '#1f7a3d', fg: '#fff'},
  OVERSTATED: {label: 'OVERSTATED', bg: '#b26a00', fg: '#fff'},
  FALSE:      {label: 'FALSE',      bg: '#a11', fg: '#fff'},
  UNTESTABLE: {label: 'UNTESTABLE', bg: 'var(--ifm-color-emphasis-400)', fg: 'var(--ifm-font-color-base)'},
};
const PED = {
  JUSTIFIED:            'justified',
  MISLEADING:           'misleading',
  'RARE-AS-CENTRAL':    'rare-as-central',
  'FREQUENCY-HIDDEN':   'frequency-hidden',
  'ORDER-QUESTIONABLE': 'order-questionable',
};
const PED_OK = k => k === 'JUSTIFIED';

function FactBadge({verdict}) {
  const f = FACT[verdict] || {label: verdict || '—', bg: 'var(--ifm-color-emphasis-300)', fg: 'inherit'};
  return (
    <span style={{
      display: 'inline-block', padding: '0.05em 0.5em', borderRadius: '0.5em',
      fontSize: '0.8em', fontWeight: 600, background: f.bg, color: f.fg, whiteSpace: 'nowrap',
    }}>{f.label}</span>
  );
}

function PedBadge({verdict}) {
  if (!verdict) return null;
  const ok = PED_OK(verdict);
  return (
    <span style={{
      display: 'inline-block', padding: '0.05em 0.5em', borderRadius: '0.5em',
      fontSize: '0.8em', border: `1px solid ${ok ? '#1f7a3d' : '#b26a00'}`,
      color: ok ? '#1f7a3d' : '#b26a00', whiteSpace: 'nowrap',
    }}>{PED[verdict] || verdict.toLowerCase()}</span>
  );
}

export default function KocherginaClaims({only}) {
  const wanted = only ? new Set(only.split(',').map(s => s.trim())) : null;
  const claims = data.claims.filter(c => !wanted || wanted.has(c.id));

  return (
    <div style={{
      border: '1px solid var(--ifm-color-emphasis-300)', borderRadius: '0.6em',
      padding: '1em', margin: '1em 0', background: 'var(--ifm-background-surface-color)',
    }}>
      <div style={{fontSize: '0.85em', color: 'var(--ifm-color-emphasis-700)', marginBottom: '0.6em'}}>
        Проверка утверждений по корпусу DCS-2021 + Уитни 1889 · сгенерировано {data.generated} ·
        источник <code>claims.yml</code> (H768)
      </div>
      {claims.map(c => (
        <div key={c.id} style={{
          padding: '0.6em 0', borderTop: '1px solid var(--ifm-color-emphasis-200)',
        }}>
          <div style={{display: 'flex', gap: '0.5em', alignItems: 'center', flexWrap: 'wrap'}}>
            <strong>{c.id}</strong>
            <FactBadge verdict={c.verdict_fact} />
            <PedBadge verdict={c.verdict_pedagogy} />
            <span style={{fontSize: '0.8em', color: 'var(--ifm-color-emphasis-600)'}}>{c.loc} · {c.kind}</span>
          </div>
          {c.claim_ru && (
            <div style={{fontSize: '0.92em', margin: '0.35em 0', fontStyle: 'italic'}}>«{c.claim_ru}»</div>
          )}
          {c.number && (
            <div style={{fontSize: '0.85em', color: 'var(--ifm-color-emphasis-800)'}}>
              <strong>Корпус:</strong> {c.number}
            </div>
          )}
          {c.mg_footnote && (
            <div style={{
              fontSize: '0.85em', margin: '0.35em 0 0', padding: '0.3em 0.6em',
              borderLeft: '3px solid var(--ifm-color-primary)',
              background: 'var(--ifm-color-emphasis-100)',
            }}>
              <strong>Частотность (M.G.):</strong> {c.mg_footnote}
              <span style={{color: 'var(--ifm-color-emphasis-600)'}}> — добавлено М.Г., отсутствует в тексте Кочергиной</span>
            </div>
          )}
          {c.ref && (
            <div style={{fontSize: '0.8em', color: 'var(--ifm-color-emphasis-600)'}}>{c.ref}</div>
          )}
        </div>
      ))}
    </div>
  );
}
