#!/usr/bin/env python3
"""Build the LessonConcordance/ page — the per-lesson cross-source concordance of
Bühler's «Руководство к элементарному курсу санскритского языка» (1923, 48 уроков).

This is the LESSON counterpart to SubjectConcordance/ (subject spine) and
Concordance/ (shared exercise sentences): for each Bühler lesson and each curated
topic inside it, it lists the matching locus in every other digitized source on
the site (Whitney §§, Kochergina занятие, Knauer Nr., Zaliznyak §§, Sangram,
Apte/Speyer/dhatu/talmud/frish where applicable), plus the lemma-coverage layer
(D2 vote) and the per-topic exception-coverage verdicts testing MG's hypothesis.

Inputs (hand-curated or register-seeded):
  - LessonConcordance/topics.yml — topic vocabulary, exception verdicts, lemma table
  - LessonConcordance/typed_link_buhler_lessons.tsv — Type-D link rows (10 columns,
    TYPED_LINK_ID_GRAMMAR.md §1 shape), linted by kosha/scripts/typed_link_lint.py

Generated — do NOT hand-edit LessonConcordance/catalog.mdx; re-run this script.
"""
import os
import sys
from collections import defaultdict

import yaml

sys.stdout.reconfigure(encoding="utf-8")
sys.stderr.reconfigure(encoding="utf-8")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "LessonConcordance")
TSV = os.path.join(OUT_DIR, "typed_link_buhler_lessons.tsv")
TOPICS = os.path.join(OUT_DIR, "topics.yml")

TARGET_LABELS = {
    "whitney-sec": "Уитни 1889",
    "zalizniak-1978-sec": "Зализняк, Очерк 1978",
    "zalizniak-1975": "Зализняк 1975",
    "zalizniak-2004": "Зализняк, Конспект 2004",
    "kochergina-lesson": "Кочергина 1998",
    "knauer-fraza": "Кнауэр, Frazy 1908",
    "sangram-article": "Sangram",
    "apte": "Apte 1885 (синтаксис)",
    "speyer": "Speyer 1886 (синтаксис)",
    "dhatu": "Гасунс, Dhātu 2014",
    "talmud": "Толчельников 2026 (morphoclass)",
    "frish": "Фриш, хрестоматия",
}


def target_url(locus):
    """Offline-resolvable loci → repo links, per TYPED_LINK_ID_GRAMMAR.md §3."""
    prefix, _, tail = locus.partition(":")
    base = "https://github.com/gasyoun/SanskritGrammar/blob/main"
    if prefix == "whitney-sec":
        return f"{base}/WhitneyGrammar_1889/", "§§ " + tail.replace("-", "–")
    if prefix == "zalizniak-1978-sec":
        return f"{base}/ZalizniakOcherk_1978/", "§§ " + tail.replace("-", "–")
    if prefix == "kochergina-lesson":
        return f"{base}/KocherginaUchebnik_1998/", "Занятие " + tail
    if prefix == "knauer-fraza":
        return f"{base}/KnauerFrazy_1908/", tail
    if prefix == "sangram-article":
        return "https://gasyoun.github.io/SanskritGrammar/sangram/articles/" + tail, tail
    if prefix == "dhatu":
        return f"{base}/GasunsDhatu_2014/", tail
    if prefix == "talmud":
        return f"{base}/TolchelnikovTalmud_2026/", tail
    return None, locus


def load_rows():
    rows = []
    with open(TSV, encoding="utf-8") as fh:
        header = fh.readline().rstrip("\n").split("\t")
        for line in fh:
            line = line.rstrip("\n")
            if not line:
                continue
            rows.append(dict(zip(header, line.split("\t"))))
    return rows


def main():
    with open(TOPICS, encoding="utf-8") as fh:
        topics_doc = yaml.safe_load(fh)

    by_anchor = defaultdict(list)
    for row in load_rows():
        by_anchor[row["anchor_id"]].append(row)

    out = []
    out.append("---")
    out.append('title: "LessonConcordance — поурочный конкорданс Бюлера"')
    out.append('sidebar_label: "LessonConcordance"')
    out.append("---")
    out.append("")
    out.append("# Поурочный конкорданс Бюлера: урок × все источники")
    out.append("")
    out.append("_Generated by [`scripts/build_lesson_concordance.py`]"
               "(https://github.com/gasyoun/SanskritGrammar/blob/main/scripts/build_lesson_concordance.py) "
               "from [`LessonConcordance/topics.yml`]"
               "(https://github.com/gasyoun/SanskritGrammar/blob/main/LessonConcordance/topics.yml) + "
               "[`typed_link_buhler_lessons.tsv`]"
               "(https://github.com/gasyoun/SanskritGrammar/blob/main/LessonConcordance/typed_link_buhler_lessons.tsv) "
               "— do not hand-edit._")
    out.append("")
    out.append("Для каждого урока [Бюлера-1923](https://gasyoun.github.io/SanskritGrammar/grammars/BuhlerLeitfaden_1923/Buhler_Unicode/)"
               " и каждой темы внутри него — соответствующий локус в остальных оцифрованных"
               " источниках сайта; план и решения D1–D16: "
               "[BUHLER_LESSON_CONCORDANCE_PLAN_2026.md](https://github.com/gasyoun/SanskritGrammar/blob/main/BUHLER_LESSON_CONCORDANCE_PLAN_2026.md)."
               " Гипотеза МГ об исключениях проверяется по каждой теме (блок «Исключения»).")
    out.append("")

    for rn, lesson in topics_doc["lessons"].items():
        out.append(f"## Урок {rn} — {lesson['title']}")
        out.append("")
        out.append(f"*Локус текста:* {lesson['mdx']}")
        out.append("")
        for topic in lesson["topics"]:
            anchor_id = f"buhler-topic:{rn}.{topic['key']}"
            rows = by_anchor.get(anchor_id, [])
            out.append(f"### {topic['title']}")
            out.append("")
            out.append(f"*Бюлер:* {topic['buhler_locus']}")
            out.append("")
            if rows:
                out.append("| Источник | Локус | Уверенность | Строк-доказательств |")
                out.append("|---|---|---|---|")
                for row in rows:
                    prefix, _, tail = row["target_locus"].partition(":")
                    label = TARGET_LABELS.get(prefix, prefix)
                    url, display = target_url(row["target_locus"])
                    loc = f"[{display}]({url})" if url else display
                    ev = row.get("evidence_count") or "—"
                    out.append(f"| {label} | {loc} | {row['confidence']} | {ev} |")
                out.append("")
            exc = topic.get("exceptions", {})
            if exc:
                out.append("**Исключения** (гипотеза: «у Бюлера много, у Зализняка-1978 нет, у Уитни всегда?»):"
                           f" **{exc.get('verdict', '—')}**")
                out.append("")
                for who in ("buhler", "whitney", "zalizniak-1978", "kochergina"):
                    if exc.get(who):
                        out.append(f"- **{who}**: {exc[who]}")
                out.append("")
            if topic.get("lemmas"):
                out.append("| Корень | Глосса | З-1975 | З-1978 | crosswalk |")
                out.append("|---|---|---|---|---|")
                for lem in topic["lemmas"]:
                    out.append(f"| {lem['root']} | {lem['gloss']} | {lem['z1975']} | {lem['z1978']} | {lem['crosswalk']} |")
                out.append("")
            if topic.get("notes"):
                out.append(f"*Примечание:* {topic['notes']}")
                out.append("")
        reg = lesson.get("claims") or []
        if reg:
            cl = ", ".join(f"[{c}](https://github.com/gasyoun/SanskritGrammar/blob/main/BuhlerLeitfaden_1923/claims.yml)"
                           for c in reg)
            out.append(f"*Регистр утверждений урока:* {cl}")
            out.append("")

    page = "\n".join(out) + "\n"
    with open(os.path.join(OUT_DIR, "catalog.mdx"), "w", encoding="utf-8") as fh:
        fh.write(page)
    n_rows = sum(len(v) for v in by_anchor.values())
    print(f"LessonConcordance/catalog.mdx written: {len(topics_doc['lessons'])} lesson(s), {n_rows} link rows")


if __name__ == "__main__":
    main()
