#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Vendor a rule -> corpus-frequency map for SandhiCollider's reader-hover surface.

Reads kosha's canonical corpus_sandhi.tsv (17 texts, per-rule counts + examples;
owned by the sandhi programme, see kosha/SANDHI_PROGRAMME.md) and emits a small
JS data module beside the widget. Only the vowel-coalescence class is kept — that
is exactly the junction family SandhiCollider models (savarna / guna / vrddhi /
yan). Each entry carries the global corpus rank (position among ALL ~9,840 sandhi
rules, so the "Nth most common sandhi" badge is honest) plus one clean example.

The JS module is committed (vendored) so the Docusaurus build never needs kosha
checked out; rerun this only to refresh after the corpus data changes.

Usage:
    python scripts/build_sandhi_frequency.py [--tsv PATH] [--out PATH]
"""
import argparse
import csv
import json
import os
import re
import sys

sys.stdout.reconfigure(encoding="utf-8")
sys.stderr.reconfigure(encoding="utf-8")

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
# kosha is a sibling repo under GitHub/ (works from a worktree too).
DEFAULT_TSV_CANDIDATES = [
    os.path.join(REPO, "..", "kosha", "data", "sandhi", "corpus_sandhi.tsv"),
    os.path.join(REPO, "..", "..", "kosha", "data", "sandhi", "corpus_sandhi.tsv"),
]
DEFAULT_OUT = os.path.join(REPO, "src", "components", "talmud", "sandhiFrequency.js")

# A minimal, self-contained junction like "ajara+amara→ajarāmaravat".
CLEAN_EXAMPLE = re.compile(r"\S+\+\S+→\S+")
# Fallback: a bare "word1+word2" junction.
BARE_JUNCTION = re.compile(r"\S+\+\S+")


def pick_example(examples_field):
    """Extract one short, clean junction from the ` · `-separated examples cell."""
    chunks = [c.strip() for c in examples_field.split(" · ") if c.strip()]
    for chunk in chunks:
        m = CLEAN_EXAMPLE.search(chunk)
        if m:
            return m.group(0)
    for chunk in chunks:
        m = BARE_JUNCTION.search(chunk)
        if m:
            return m.group(0)
    return ""


def resolve_tsv(explicit):
    if explicit:
        return explicit
    for cand in DEFAULT_TSV_CANDIDATES:
        if os.path.exists(cand):
            return cand
    sys.exit(
        "corpus_sandhi.tsv not found; pass --tsv or clone kosha as a sibling repo.\n"
        "Tried:\n  " + "\n  ".join(os.path.normpath(c) for c in DEFAULT_TSV_CANDIDATES)
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tsv", default=None, help="path to kosha corpus_sandhi.tsv")
    ap.add_argument("--out", default=DEFAULT_OUT, help="output .js module path")
    args = ap.parse_args()

    tsv = resolve_tsv(args.tsv)
    with open(tsv, encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh, delimiter="\t"))

    # Global rank = position when sorted by corpus frequency (1-based, all classes).
    rows.sort(key=lambda r: int(r["global_count"]), reverse=True)
    for i, r in enumerate(rows, start=1):
        r["_rank"] = i
    total_rules = len(rows)

    table = {}
    for r in rows:
        if r["category"] != "vowel coalescence":
            continue
        lhs, _, rhs = r["rule"].partition(" → ")
        lhs = lhs.strip()
        if len(lhs.split()) != 2:  # collider only queries two-vowel junctions
            continue
        if lhs in table:  # keep the highest-count row per input pair (already sorted)
            continue
        table[lhs] = {
            "out": rhs.strip(),
            "count": int(r["global_count"]),
            "pct": float(r["global_pct"]),
            "rank": r["_rank"],
            "nTexts": int(r["n_texts"]),
            "example": pick_example(r["examples"]),
        }

    payload = json.dumps(table, ensure_ascii=False, indent=2, sort_keys=True)
    header = (
        "// AUTO-GENERATED by scripts/build_sandhi_frequency.py — do not hand-edit.\n"
        "// Source: kosha data/sandhi/corpus_sandhi.tsv (17 texts; sandhi programme).\n"
        "// Vowel-coalescence junctions only — the family SandhiCollider models.\n"
        "// Keyed by \"<left> <right>\" input pair; `rank` is the junction's position\n"
        f"// among all {total_rules} corpus sandhi rules by frequency (1 = most common).\n"
        f"export const TOTAL_SANDHI_RULES = {total_rules};\n"
        "export const SANDHI_FREQ = "
    )
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(header + payload + ";\n")

    print(f"wrote {os.path.relpath(args.out, REPO)}: {len(table)} junctions "
          f"(of {total_rules} corpus rules)")


if __name__ == "__main__":
    main()
