#!/usr/bin/env python3
"""Render scripts/data/catalog.json into Concordance/catalog.mdx — the
generated Docusaurus page. Never hand-edit the .mdx; re-run this after
build_catalog.py (same source+generate pattern as errata.yml -> ERRATA.md)."""
import json
import os
import sys

sys.stdout.reconfigure(encoding="utf-8")
sys.stderr.reconfigure(encoding="utf-8")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(ROOT, "scripts", "data")
OUT_DIR = os.path.join(ROOT, "Concordance")
os.makedirs(OUT_DIR, exist_ok=True)

BOOK_COLS = ["buhler", "knauer", "kochergina"]
BOOK_HEAD = {"buhler": "Bühler", "knauer": "Knauer", "kochergina": "Kochergina"}


def cell(r, book):
    lessons = r["books"].get(book)
    return ", ".join(lessons) if lessons else "—"


def main():
    with open(os.path.join(DATA_DIR, "catalog.json"), encoding="utf-8") as f:
        rows = json.load(f)

    n_all3 = sum(1 for r in rows if len(r["books"]) == 3)
    n_bk = sum(1 for r in rows if set(r["books"]) == {"buhler", "knauer"})
    n_bko = sum(1 for r in rows if set(r["books"]) == {"buhler", "kochergina"})
    n_ko = sum(1 for r in rows if set(r["books"]) == {"knauer", "kochergina"})

    lines = []
    lines.append("---")
    lines.append('title: "Concordance — shared exercise sentences"')
    lines.append('sidebar_label: "Concordance"')
    lines.append("---")
    lines.append("")
    lines.append("# Bühler / Knauer / Kochergina — concordance of shared exercise sentences")
    lines.append("")
    lines.append("_Generated by [`scripts/build_catalog.py`](https://github.com/gasyoun/SanskritGrammar/blob/main/scripts/build_catalog.py) "
                  "+ [`scripts/render_catalog_mdx.py`](https://github.com/gasyoun/SanskritGrammar/blob/main/scripts/render_catalog_mdx.py) "
                  "from [`scripts/data/matches.json`](https://github.com/gasyoun/SanskritGrammar/blob/main/scripts/data/matches.json) — do not hand-edit._")
    lines.append("")
    lines.append(
        "Sanskrit grammar textbooks have long borrowed each other's model "
        "sentences. This page cross-references the exercise sentences of "
        "three textbooks in this repo — "
        "[Bühler](https://gasyoun.github.io/SanskritGrammar/grammars/BuhlerLeitfaden_1923/Buhler_Unicode) "
        "(German first edition 1878; this repo carries the 1923 Stockholm "
        "electronic reprint as a text proxy — the exercises are not known to "
        "have been revised between editions, but this has not been verified "
        "against the 1878 print), "
        "[Knauer](https://gasyoun.github.io/SanskritGrammar/grammars/KnauerFrazy_1908/Frazy-Knauer-03.05.2023) "
        "(1908), and "
        "[Kochergina](https://gasyoun.github.io/SanskritGrammar/grammars/KocherginaUchebnik_1998/Kochergina_unicode) "
        "(1998) — and lists which sentences recur, ordered chronologically "
        "by the earliest book each one is attested in."
    )
    lines.append("")
    lines.append("## Method (first pass — see caveats)")
    lines.append("")
    lines.append(
        "[`scripts/extract_sentences.py`](https://github.com/gasyoun/SanskritGrammar/blob/main/scripts/extract_sentences.py) "
        "pulls Devanagari- and IAST-script sentence-like runs out of each "
        "book's `.mdx` (tagging which script each was originally set in), "
        "normalizes whitespace/footnote markers, and computes pairwise "
        "matches with `difflib.SequenceMatcher` (similarity ≥ 0.82) within "
        "each script pool. [`scripts/build_catalog.py`](https://github.com/gasyoun/SanskritGrammar/blob/main/scripts/build_catalog.py) "
        "clusters the pairwise matches (union-find) into single rows and "
        "picks a Devanagari exemplar for display when one is available."
    )
    lines.append("")
    lines.append(
        "**Caveats:** (1) Devanagari matches are the primary signal — all "
        "three books share Devanagari unambiguously, whereas IAST runs "
        "overlap heavily with glossary/paradigm-table noise (verb-class "
        "codes, case labels), so IAST matches are kept only when both sides "
        "have ≥4 words. (2) Near-matches below 1.0 are almost all spelling/"
        "transcription variants of the same sentence (e.g. *च्छ* vs *छ*), "
        "spot-checked by hand — see the review pass in "
        "[H311](https://github.com/gasyoun/Uprava/blob/main/handoffs/H311-Sonnet_SanskritGrammar_buhler-knauer-kochergina-concordance_07.07.26.md). "
        "(3) This is an automated first pass, not a philological edition — "
        "it will miss paraphrased reuse (same content, different wording) "
        "and may include coincidental short-sentence collisions; treat "
        "single-book-pair rows with short text as lower confidence than the "
        "all-three-books rows. (4) Sentence numbering below is catalog-only "
        "(`C0001`…) — the source books' own numbering is untouched."
    )
    lines.append("")
    lines.append(
        f"**{len(rows)} shared-sentence clusters found:** {n_all3} attested in "
        f"all three books, {n_bk} shared only between Bühler and Knauer, "
        f"{n_bko} only between Bühler and Kochergina, {n_ko} only between "
        "Knauer and Kochergina."
    )
    lines.append("")
    lines.append("## Catalog")
    lines.append("")
    lines.append("| № | Earliest | Sentence | Bühler (lesson) | Knauer (Nr.) | Kochergina (занятие) |")
    lines.append("|---|---|---|---|---|---|")
    for r in rows:
        text = r["text"].replace("|", "\\|")
        lines.append(
            f"| {r['catalog_id']} | {r['earliest_year']} | {text} "
            f"| {cell(r, 'buhler')} | {cell(r, 'knauer')} | {cell(r, 'kochergina')} |"
        )
    lines.append("")

    out_path = os.path.join(OUT_DIR, "catalog.mdx")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {out_path} ({len(rows)} rows)", file=sys.stderr)


if __name__ == "__main__":
    main()
