#!/usr/bin/env python3
"""Generate the Sangram C2 TOC pages from sangram/toc/data/articles.json.

Emits (all marked auto-generated, do not hand-edit):
  sangram/toc/00-network-overview.mdx        overview + domain-level Mermaid
  sangram/toc/NN-<domain-slug>.mdx  (x7)     per-domain article tables + prerequisite graphs

Derived witness layer: per-chapter coverage of the 9 non-Whitney works
(whitney_chapter_coverage.json, transcribed from SubjectConcordance/catalog.mdx)
is rendered on the pages; curated witnesses live only in articles.json.

Usage:
  python scripts/toc_build_pages.py           write pages
  python scripts/toc_build_pages.py --check   exit 1 if on-disk pages differ (used by toc_validate.py)
"""
import json
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

ROOT = Path(__file__).resolve().parents[1]
TOC = ROOT / "sangram" / "toc"
DATA = TOC / "data"

GEN_MARK = ("{/* AUTO-GENERATED by scripts/toc_build_pages.py from "
            "sangram/toc/data/articles.json -- do not hand-edit; "
            "edit the registry and re-run. */}")

WIKISOURCE = "https://en.wikisource.org/wiki/Sanskrit_Grammar_%28Whitney%29/Chapter_"
BLOB = "https://github.com/gasyoun/SanskritGrammar/blob/main/"
GLYPH = {2: "●", 1: "○", 0: "—"}


def load():
    reg = json.loads((DATA / "articles.json").read_text(encoding="utf-8"))
    cov = json.loads((DATA / "whitney_chapter_coverage.json").read_text(encoding="utf-8"))
    return reg, cov


def chapter_of(anchor: str, chapters: dict) -> str:
    lo = int(anchor.split(":")[1].split("-")[0])
    for ch, row in chapters.items():
        a, b = (int(x) for x in row["sections"].split("-"))
        if a <= lo <= b:
            return ch
    return ""


def sec_label(anchor: str) -> str:
    body = anchor.split(":")[1]
    return "§" + body.replace("-", "–")


def mermaid_id(aid: str) -> str:
    return aid.replace("-", "_")


def short(title: str, n: int = 30) -> str:
    return title if len(title) <= n else title[: n - 1].rstrip() + "…"


def build_domain_page(dom, arts, all_by_id, cov, works_by_slug):
    ch_map = cov["chapters"]
    L = []
    L.append("---")
    L.append(f"title: \"{dom['title_ru']} — статьи ядра\"")
    L.append(f"sidebar_label: \"{dom['order']}. {dom['title_ru']}\"")
    L.append(f"sidebar_position: {dom['order'] + 2}")
    L.append(f"description: Домен «{dom['title_ru']}» сети-оглавления Sangram (C2) — "
             f"{len(arts)} статей ядра со стабильными ID, пререквизитами, корпусными запросами и свидетелями.")
    L.append("---")
    L.append("")
    L.append(GEN_MARK)
    L.append("")
    L.append(f"# {dom['title_ru']} ({dom['code']})")
    L.append("")
    L.append(f"Домен {dom['order']} из 7 сети-оглавления [C2](./SANGRAM_TOC_NETWORK.mdx): "
             f"**{len(arts)} статей ядра**. ID стабильны и append-only; "
             f"пререквизиты — ребра сети; запрос — эскиз намерения по грамматике C2 "
             f"(исполнимая форма и ворота — [метод C3](../SANGRAM_CORPUS_EVIDENCE_METHOD.mdx)).")
    L.append("")
    L.append("| ID | Статья | Кластер | Пререквизиты | Уитни | Прочие свидетели | Запрос (эскиз) | Слот C6 |")
    L.append("|---|---|---|---|---|---|---|---|")
    notes = []
    for a in arts:
        pre = ", ".join(a["prerequisites"]) or "—"
        wh = []
        for anc in a["whitney"]:
            ch = chapter_of(anc, ch_map)
            wh.append(f"[{sec_label(anc)}]({WIKISOURCE}{ch})" if ch else sec_label(anc))
        wh_cell = "; ".join(wh) or "—"
        others = "; ".join(
            f"{works_by_slug[w['work']]['title_ru'].split(',')[0]}: {w['locus']}"
            for w in a["witnesses"] if w["work"] != "whitney-1889") or "—"
        slots = ", ".join(f"`{s}`" for s in a.get("c6_slots", [])) or "—"
        L.append(f"| {a['id']} | **{a['title_ru']}** | {a['cluster']} | {pre} "
                 f"| {wh_cell} | {others} | `{a['query']['sketch']}` | {slots} |")
        if a["query"].get("note"):
            notes.append((a["id"], a["query"]["note"]))
    L.append("")
    if notes:
        L.append("### Оговорки к запросам")
        L.append("")
        for aid, note in notes:
            L.append(f"- **{aid}** — {note}")
        L.append("")
    # intra-domain prerequisite graph
    intra = [(p, a["id"]) for a in arts for p in a["prerequisites"]
             if p.split("-")[1] == dom["code"]]
    if intra:
        L.append("### Пререквизиты внутри домена")
        L.append("")
        L.append("```mermaid")
        L.append("flowchart TD")
        L.append(f"  accTitle: Пререквизиты внутри домена {dom['title_ru']}")
        L.append("  accDescr: Ориентированный ациклический граф: ребро ведет от статьи-пререквизита к статье, которая на нее опирается.")
        used = {x for e in intra for x in e}
        for aid in sorted(used):
            L.append(f"  {mermaid_id(aid)}[\"{aid.rsplit('-', 1)[1]} {short(all_by_id[aid]['title_ru'])}\"]")
        for p, c in intra:
            L.append(f"  {mermaid_id(p)} --> {mermaid_id(c)}")
        L.append("```")
        L.append("")
    cross = [(p, a["id"]) for a in arts for p in a["prerequisites"]
             if p.split("-")[1] != dom["code"]]
    if cross:
        L.append("### Пререквизиты из других доменов")
        L.append("")
        for p, c in cross:
            L.append(f"- {c} ← **{p}** ({all_by_id[p]['title_ru']})")
        L.append("")
    # derived coverage layer
    chs = sorted({chapter_of(anc, ch_map) for a in arts for anc in a["whitney"]
                  if chapter_of(anc, ch_map)},
                 key=lambda c: int(ch_map[c]["sections"].split("-")[0]))
    if chs:
        L.append("### Покрытие глав Уитни другими работами (производный слой)")
        L.append("")
        L.append(f"Автоматическая первичная разметка по [предметному конкордансу]({BLOB}SubjectConcordance/catalog.mdx) "
                 "(куррированный ключевой лексикон, не филологическая карта): ● — покрыто, ○ — упомянуто, — — не найдено. "
                 "Куррированные свидетели каждой статьи — в таблице выше и в реестре.")
        L.append("")
        wslugs = [w["slug"] for w in works_by_slug.values() if w["slug"] != "whitney-1889"]
        head = " | ".join(works_by_slug[s]["title_ru"].split(",")[0] for s in wslugs)
        L.append(f"| Глава Уитни | §§ | {head} |")
        L.append("|---|---|" + "---|" * len(wslugs))
        for ch in chs:
            row = ch_map[ch]
            cells = " | ".join(GLYPH[row[s]] for s in wslugs)
            L.append(f"| {ch} | {row['sections'].replace('-', '–')} | {cells} |")
        L.append("")
    L.append("_Автогенерировано `scripts/toc_build_pages.py` из реестра C2._")
    L.append("")
    return "\n".join(L)


def build_overview(reg, cov):
    doms = sorted(reg["domains"], key=lambda d: d["order"])
    arts = reg["articles"]
    by_dom = {d["code"]: [a for a in arts if a["id"].split("-")[1] == d["code"]] for d in doms}
    edges = [(p.split("-")[1], a["id"].split("-")[1])
             for a in arts for p in a["prerequisites"]]
    n_edges = sum(len(a["prerequisites"]) for a in arts)
    n_slots = sum(len(a.get("c6_slots", [])) for a in arts)
    L = []
    L.append("---")
    L.append("title: \"Сеть-оглавление статей — обзор\"")
    L.append("sidebar_label: \"Обзор сети\"")
    L.append("sidebar_position: 2")
    L.append(f"description: Обзор сети-оглавления Sangram (C2) — {len(arts)} статей ядра "
             f"в 7 доменах, {n_edges} ребер пререквизитов, кросс-связи с программой C6.")
    L.append("---")
    L.append("")
    L.append(GEN_MARK)
    L.append("")
    L.append("# Сеть-оглавление статей Sangram — обзор")
    L.append("")
    L.append(f"**{len(arts)} статей ядра** в **7 доменах** [хартии](../SANGRAM_CHARTER_2026_2031.mdx) § 5, "
             f"**{n_edges} ребер** пререквизитов, **{n_slots} слотов** [программы C6](../SANGRAM_SYNTAX_SEMANTICS_PROGRAM_W3_W4.mdx) "
             f"замаплено в реестр. Правила сети — [контракт C2](./SANGRAM_TOC_NETWORK.mdx); "
             f"машиночитаемый реестр — [`articles.json`]({BLOB}sangram/toc/data/articles.json).")
    L.append("")
    L.append("| Домен | Код | Статей | Кластеры |")
    L.append("|---|---|---|---|")
    for d in doms:
        da = by_dom[d["code"]]
        clusters = " · ".join(dict.fromkeys(a["cluster"] for a in da))
        L.append(f"| [{d['title_ru']}](./{d['order']:02d}-{d['slug']}.mdx) | {d['code']} | {len(da)} | {clusters} |")
    L.append("")
    L.append("### Зависимости между доменами")
    L.append("")
    L.append("```mermaid")
    L.append("flowchart LR")
    L.append("  accTitle: Зависимости между семью доменами сети-оглавления")
    L.append("  accDescr: Стрелка от домена-пререквизита к домену, статьи которого на него опираются; подпись — число ребер.")
    for d in doms:
        L.append(f"  {d['code']}[\"{d['title_ru']} ({len(by_dom[d['code']])})\"]")
    agg = {}
    for src, dst in edges:
        if src != dst:
            agg[(src, dst)] = agg.get((src, dst), 0) + 1
    for (src, dst), n in sorted(agg.items()):
        L.append(f"  {src} -->|{n}| {dst}")
    L.append("```")
    L.append("")
    L.append("_Автогенерировано `scripts/toc_build_pages.py` из реестра C2._")
    L.append("")
    return "\n".join(L)


def main() -> int:
    check = "--check" in sys.argv
    reg, cov = load()
    works_by_slug = {w["slug"]: w for w in reg["works"]}
    all_by_id = {a["id"]: a for a in reg["articles"]}
    doms = sorted(reg["domains"], key=lambda d: d["order"])

    pages = {TOC / "00-network-overview.mdx": build_overview(reg, cov)}
    for d in doms:
        arts = [a for a in reg["articles"] if a["id"].split("-")[1] == d["code"]]
        pages[TOC / f"{d['order']:02d}-{d['slug']}.mdx"] = build_domain_page(
            d, arts, all_by_id, cov, works_by_slug)

    stale = []
    for path, content in pages.items():
        on_disk = path.read_text(encoding="utf-8") if path.exists() else None
        if on_disk != content:
            stale.append(path.name)
            if not check:
                path.write_text(content, encoding="utf-8", newline="\n")
    if check:
        if stale:
            print("out of sync: " + ", ".join(stale))
            return 1
        print("pages in sync")
        return 0
    print(f"wrote {len(pages)} pages ({len(stale)} changed)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
