#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""H1018: print-ready sheet for the 750 genuine MW roots (Приложение 7, Фаза 4).

Sibling of scripts/build_errata_print_sheet.py and the same contract: the
compact print asset stays SEPARATE from the book body — the appendix page
(`Приложения издания 2026.mdx`) already rules that printing the full list
in the chapter text is impractical (нецелесообразно) and keeps only an
illustrative excerpt there; MG's ruling on H1018 (Route 2) is to typeset
the full list as its own print-styled insert instead, mirroring the errata
sheets' «печатный лист» pattern rather than inlining it into the .mdx.

Consumes:
  mw_genuine_roots.tsv  (generated by mw_genuine_roots.py — genuine + enrichment)

Emits:
  APPENDIX7_PRINT_SHEET.html — A4 print-styled, dense multi-column list of the
  750 genuine roots (★ √root — кл. classes · DCS freq (rank) · N словарей),
  alphabetical by IAST, same ordering/format as mw_genuine_roots_list.md.

APPENDIX7_PRINT_SHEET.html is GENERATED and must never be edited by hand.

Usage:
    python GasunsDhatu_2014/revision-2026/mw_genuine_roots_print_sheet.py
"""

import csv
import datetime
import html
import io
import os
import sys

sys.stdout.reconfigure(encoding="utf-8")
sys.stderr.reconfigure(encoding="utf-8")

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
TSV_IN = os.path.join(OUT_DIR, "mw_genuine_roots.tsv")
HTML_OUT = os.path.join(OUT_DIR, "APPENDIX7_PRINT_SHEET.html")

STYLE = """
  @page { size: A4; margin: 16mm; }
  body { font-family: 'PT Serif', Georgia, 'Times New Roman', serif; color: #111;
         max-width: 190mm; margin: 0 auto; padding: 12px; line-height: 1.4; }
  h1 { font-size: 18px; margin: 0 0 2px; letter-spacing: 0.03em; }
  p.work { font-size: 13px; font-style: italic; margin: 0 0 4px; }
  p.method { font-size: 11px; color: #333; margin: 0 0 14px; }
  div.cols { column-count: 3; column-gap: 18px; font-size: 10.5px; }
  p.entry { margin: 0 0 2px; break-inside: avoid; }
  p.small { font-size: 10px; color: #444; margin-top: 14px; column-span: all; }
  @media print { body { padding: 0; } p.small { page-break-inside: avoid; } }
  @media (max-width: 700px) { div.cols { column-count: 1; } }
"""


def load_genuine(path):
    with io.open(path, encoding="utf-8") as f:
        rows = list(csv.DictReader(f, delimiter="\t"))
    genuine = [r for r in rows if r.get("genuine") == "1"]

    def sort_key(r):
        try:
            l = int(float(r.get("mw_L") or 0))
        except ValueError:
            l = 0
        return ((r.get("root_iast") or "").lower(), l)

    genuine.sort(key=sort_key)
    return genuine, len(rows)


def render_entry(r):
    cl = (r.get("classes") or "").strip()
    parts = []
    if cl:
        parts.append(f"кл. {html.escape(cl)}")
    freq = (r.get("dcs_freq") or "0").strip()
    rank = (r.get("dcs_rank") or "").strip()
    if freq and freq != "0":
        parts.append(f"DCS {html.escape(freq)}" + (f" #{html.escape(rank)}" if rank else ""))
    else:
        parts.append("DCS —")
    n = (r.get("n_dicts") or "0").strip()
    parts.append(f"{html.escape(n)} слов.")
    root = html.escape(r.get("root_iast") or "")
    return f'    <p class="entry">★ √<i>{root}</i> — {" · ".join(parts)}</p>'


def render_sheet(genuine, total):
    entries = "\n".join(render_entry(r) for r in genuine)
    today = datetime.date.today().strftime("%d.%m.%Y")
    return f"""<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="utf-8">
<title>Приложение 7 — Подлинные корни словаря Монье-Уильямса</title>
<style>{STYLE}</style>
</head>
<body>
<h1>ПРИЛОЖЕНИЕ 7. ПОДЛИННЫЕ КОРНИ СЛОВАРЯ МОНЬЕ-УИЛЬЯМСА</h1>
<p class="work">Гасунс М. Р., «Состав и строй древнеиндийских глагольных корней», 2-е изд.</p>
<p class="method">★ = подлинный корень (verb_type=genuineroot в кёльнской цифровой MW,
{len(genuine)} из {total} корневых статей); формат: √корень — классы спряжения ·
частота в DCS (ранг) · число подтверждающих словарей (root_oracle). Список по
алфавиту IAST.</p>
<div class="cols">
{entries}
</div>
<p class="small">Источник разметки: csl-orig v02/mw/mw_roots.tsv (колонка verb_type).
Обогащение: WhitneyRoots/crosswalk/roots.csv (частота/ранг DCS), csl-orig
v02/etymology_stats/root_oracle.tsv (число словарей-источников). Лист сгенерирован
{today} скриптом mw_genuine_roots_print_sheet.py из mw_genuine_roots.tsv
(полный метод и обогащённая таблица всех {total} статей — там же, в папке
revision-2026; текстовый разбор — Приложение 7 книги); файл
APPENDIX7_PRINT_SHEET.html не редактируется вручную.</p>
</body>
</html>
"""


def main():
    genuine, total = load_genuine(TSV_IN)
    with io.open(HTML_OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(render_sheet(genuine, total))
    print(f"-> {os.path.relpath(HTML_OUT)} ({len(genuine)} корней)")


if __name__ == "__main__":
    main()
