#!/usr/bin/env python
"""Generate the A60 central table — "grammar claims the corpus does not confirm" (H773 Q1).

Joins two hand-edited sources and writes ONE generated markdown file:

    ../../../KocherginaUchebnik_1998/claims.yml   (H768: the verified two-axis register — SOURCE)
    ./divergence_classes.yml                       (H773: the divergence-class layer — SOURCE)
        -> ./TABLE_grammar-claims-corpus-denies_A60.md   (generated — never hand-edit)

The table is the OVERSTATED/FALSE fact-axis subset (the claims the corpus does NOT confirm),
each row carrying its corpus number, its H773 divergence class, and its pedagogy verdict, plus
an aggregation by class / kind / pedagogy and the register-composition context. A small second
table lists the UNTESTABLE claims (the corpus CANNOT adjudicate them — distinct from "denies").

BOUNDARY: this script only READS claims.yml; the fact-verdicts and DCS numbers are H768's, not
re-derived here (roadmap rule "corpus counts belong to VisualDCS — consume, do not re-derive").

Provenance: H773 / paper A60, Opus 4.8 (claude-opus-4-8), 12-07-2026.

Usage:  python build_divergence_table.py         # regenerate the table
        python build_divergence_table.py --check  # exit 1 if any OVERSTATED/FALSE id is unclassified
"""

import sys
import datetime
from pathlib import Path

import yaml

sys.stdout.reconfigure(encoding="utf-8")
sys.stderr.reconfigure(encoding="utf-8")

HERE = Path(__file__).resolve().parent
CLAIMS_YML = HERE.parent.parent.parent / "KocherginaUchebnik_1998" / "claims.yml"
CLASSES_YML = HERE / "divergence_classes.yml"
OUT_MD = HERE / "TABLE_grammar-claims-corpus-denies_A60.md"
TODAY = datetime.date.today()

DENIES = ("OVERSTATED", "FALSE")          # "corpus does not confirm" — the paper's core subset
FACT_BADGE = {"OVERSTATED": "🟠 OVERSTATED", "FALSE": "❌ FALSE", "UNTESTABLE": "⚪ UNTESTABLE"}


def ddmmyyyy(d):
    return d.strftime("%d-%m-%Y")


def norm_fact(v):
    """YAML reads unquoted TRUE/FALSE as booleans — coerce back to the verdict vocabulary."""
    if v is True:
        return "TRUE"
    if v is False:
        return "FALSE"
    return v


def cell(s):
    return ("" if s is None else str(s)).replace("|", "\\|").replace("\n", " ").strip()


def short(s, n=90):
    s = " ".join(("" if s is None else str(s)).split())
    return s if len(s) <= n else s[: n - 1] + "…"


def grammar_label(entry, work):
    book = entry.get("book")
    if book:
        return book.replace("-", " ").title()
    return "Kochergina 1998" if "Kochergina" in (work or "") else short(work, 30)


def main():
    check = "--check" in sys.argv[1:]

    claims = yaml.safe_load(CLAIMS_YML.read_text(encoding="utf-8")) or {}
    work = claims.get("work", "")
    entries = claims.get("entries", []) or []

    classes_doc = yaml.safe_load(CLASSES_YML.read_text(encoding="utf-8")) or {}
    class_defs = classes_doc.get("classes", {}) or {}
    assign = classes_doc.get("assignments", {}) or {}

    # Register composition (all verdicted claims) — context for "the corpus mostly confirms".
    comp = {}
    for e in entries:
        comp[norm_fact(e.get("verdict_fact"))] = comp.get(norm_fact(e.get("verdict_fact")), 0) + 1
    total = len(entries)

    denies = [e for e in entries if norm_fact(e.get("verdict_fact")) in DENIES]
    untestable = [e for e in entries if norm_fact(e.get("verdict_fact")) == "UNTESTABLE"]

    # Every OVERSTATED/FALSE id must carry a class assignment.
    unassigned = [e.get("id") for e in denies if e.get("id") not in assign]
    if unassigned:
        print(f"ERROR: {len(unassigned)} OVERSTATED/FALSE claim(s) without a divergence class: "
              f"{', '.join(unassigned)}", file=sys.stderr)
        print("Add them to divergence_classes.yml (assignments:).", file=sys.stderr)
        sys.exit(1)
    if check:
        print(f"OK: all {len(denies)} OVERSTATED/FALSE claims classified.")
        return

    def class_of(e):
        return assign.get(e.get("id"), {}).get("class")

    denies.sort(key=lambda e: (class_of(e), e.get("id")))

    # Aggregations over the OVERSTATED/FALSE subset.
    by_class, by_kind, by_ped, by_fact = {}, {}, {}, {}
    for e in denies:
        by_class[class_of(e)] = by_class.get(class_of(e), 0) + 1
        by_kind[e.get("kind")] = by_kind.get(e.get("kind"), 0) + 1
        by_ped[e.get("verdict_pedagogy")] = by_ped.get(e.get("verdict_pedagogy"), 0) + 1
        by_fact[norm_fact(e.get("verdict_fact"))] = by_fact.get(norm_fact(e.get("verdict_fact")), 0) + 1

    L = []
    L += [
        "# Grammar claims the corpus does not confirm — central table (A60)",
        "",
        "_Auto-generated by [`build_divergence_table.py`](build_divergence_table.py) from "
        "[`KocherginaUchebnik_1998/claims.yml`](../../../KocherginaUchebnik_1998/claims.yml) (H768, "
        "the verified register) + [`divergence_classes.yml`](divergence_classes.yml) (H773, the "
        "divergence-class layer). **Do not edit this file by hand** — edit the two sources and re-run._",
        "",
        f"_Generated: {ddmmyyyy(TODAY)} · Opus 4.8 (`claude-opus-4-8`), H773 Q1 · "
        f"{len(denies)} divergences (of {total} verified claims)._",
        "",
        "## Register composition (context)",
        "",
        f"Of **{total}** verified assertions in Kochergina 1998, the corpus **confirms the large "
        f"majority**. This paper is about the minority it does not:",
        "",
        "| verdict_fact | n | share |",
        "|--|--:|--:|",
    ]
    for v in ("TRUE", "OVERSTATED", "FALSE", "UNTESTABLE"):
        if comp.get(v):
            L.append(f"| {FACT_BADGE.get(v, v)} | {comp[v]} | {100*comp[v]/total:.1f}% |")
    L += [
        "",
        f"The **{len(denies)}** OVERSTATED/FALSE claims ({100*len(denies)/total:.1f}%) are the "
        f"\"corpus does not confirm\" subset below; the {comp.get('UNTESTABLE', 0)} UNTESTABLE claims "
        "(corpus *cannot* adjudicate) are listed separately.",
        "",
        "## Central table — the divergences",
        "",
        "Columns: divergence class · ID · grammar · claim (abridged) · kind · fact-verdict · corpus "
        "number (the evidence) · pedagogy verdict.",
        "",
        "| Class | ID | Grammar | Claim (abridged) | Kind | Fact | Corpus number / counter-evidence | Pedagogy |",
        "|--|--|--|--|--|--|--|--|",
    ]
    for e in denies:
        c = class_of(e)
        cname = class_defs.get(c, {}).get("name", "?")
        L.append(
            f"| **{c} {cname}** | {cell(e.get('id'))} | {grammar_label(e, work)} | "
            f"{short(e.get('claim_ru'), 80)} | {cell(e.get('kind'))} | "
            f"{FACT_BADGE.get(norm_fact(e.get('verdict_fact')))} | {short(e.get('number'), 150)} | "
            f"{cell(e.get('verdict_pedagogy'))} |"
        )

    L += ["", "## Aggregation", "", "**By divergence class:**", "",
          "| Class | Name | n |", "|--|--|--:|"]
    for c in sorted(class_defs):
        L.append(f"| {c} | {class_defs[c].get('name','')} | {by_class.get(c, 0)} |")

    L += ["", "**By claim kind:**", "", "| Kind | n |", "|--|--:|"]
    for k, n in sorted(by_kind.items(), key=lambda kv: -kv[1]):
        L.append(f"| {cell(k)} | {n} |")

    L += ["", "**By pedagogy verdict:**", "", "| Pedagogy | n |", "|--|--:|"]
    for p, n in sorted(by_ped.items(), key=lambda kv: -kv[1]):
        L.append(f"| {cell(p)} | {n} |")

    L += ["", "**By fact verdict:**", "", "| Fact | n |", "|--|--:|"]
    for v in ("OVERSTATED", "FALSE"):
        if by_fact.get(v):
            L.append(f"| {FACT_BADGE[v]} | {by_fact[v]} |")

    # The structural correspondence worth stating.
    L += [
        "",
        "**Class ⇄ pedagogy correspondence.** The over-generalisation class (1) coincides exactly "
        "with the `MISLEADING` pedagogy verdict, and the frequency/conditioning classes (2, 4) with "
        "`FREQUENCY-HIDDEN`: an absolute rule with an unstated escape hatch reads as *misleading*, "
        "while a minority/variant reframed as the norm reads as *frequency-hidden*. The two axes "
        "(fact and pedagogy, from H768) and the divergence typology (H773) are not independent — the "
        "typology explains the pedagogy verdict.",
    ]

    if untestable:
        L += [
            "",
            "## Separate bucket — claims the corpus CANNOT adjudicate (UNTESTABLE)",
            "",
            "Not divergences (the corpus does not *deny* them) — assertions whose count base "
            "Kochergina does not disclose, or that the DCS-2021 export cannot tag. Flagged, not scored.",
            "",
            "| ID | Grammar | Claim (abridged) | Why untestable |",
            "|--|--|--|--|",
        ]
        for e in untestable:
            L.append(f"| {cell(e.get('id'))} | {grammar_label(e, work)} | "
                     f"{short(e.get('claim_ru'), 80)} | {short(e.get('number'), 140)} |")

    L += ["", f"_Auto-generated by [`build_divergence_table.py`](build_divergence_table.py) on "
          f"{ddmmyyyy(TODAY)}. Source of record for the A60 central table; the outline embeds a copy._", ""]

    OUT_MD.write_text("\n".join(L), encoding="utf-8")

    # Console summary (also the numbers quoted in the outline + commit message).
    print(f"Wrote {OUT_MD.name}")
    print(f"  register: {total} verified — " +
          ", ".join(f"{v} {comp[v]}" for v in ("TRUE", "OVERSTATED", "FALSE", "UNTESTABLE") if comp.get(v)))
    print(f"  divergences (OVERSTATED/FALSE): {len(denies)}")
    print(f"  by class: " + ", ".join(f"{c}={by_class.get(c,0)}" for c in sorted(class_defs)))
    print(f"  by kind:  " + ", ".join(f"{k}={n}" for k, n in sorted(by_kind.items(), key=lambda kv: -kv[1])))
    print(f"  by ped:   " + ", ".join(f"{p}={n}" for p, n in sorted(by_ped.items(), key=lambda kv: -kv[1])))


if __name__ == "__main__":
    main()
