#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gen_footnote_proposals.py — seed footnote-proposals/proposals.yml with the
Phase-3 data-derived enrichments awaiting the author's (Ivan) approval.

Emits, with exact evidence citations pulled from data/whitney_talmud.json:
  * FN-0001 — a METHODOLOGY proposal for the whole computed-Ряд column of
    Приложение 1 (approve the derivation, not per-root).
  * FN-0002 — a METHODOLOGY proposal for the advisory seṭ column.
  * freq-note proposals for the top distinct high-frequency roots (first cohort).

Every proposal is status=pending / approved_by=null — nothing enters the author's
running text without an `approved_by: Ivan` line (footnote-proposals/README.md).

Usage:  python tools/gen_footnote_proposals.py
"""
import json
import os
import sys

sys.stdout.reconfigure(encoding="utf-8")

HERE = os.path.dirname(os.path.abspath(__file__))
FOLDER = os.path.dirname(HERE)
JSON = os.path.join(FOLDER, "data", "whitney_talmud.json")
OUT = os.path.join(FOLDER, "footnote-proposals", "proposals.yml")

TOP_N = 12  # distinct high-frequency roots to flag as first-cohort teaching material

HEADER = """# footnote-proposals/proposals.yml — data-derived enrichment proposals for the
# Talmud санскрита, each awaiting explicit approval by the author
# (Ivan / I.E. Tolchelnikov). See README.md in this folder for the rule.
#
# Schema (from TolchelnikovTalmud_2026/IMPROVEMENT_PLAN.md):
#   id:          FN-#### (append-only, never reuse)
#   target:      { section: "II", root: "√kṛ" }   # or an appendix row
#   type:        freq-note | whitney-ref | set-correction | missing-root | paradigm-check
#   proposal:    the footnote text proposed for the author's running text
#   evidence:    exact data source (file + row) backing the proposal
#   status:      pending -> approved (Ivan) -> applied ; or rejected (stays logged)
#   approved_by: null until Ivan approves
#
# Generated by tools/gen_footnote_proposals.py from data/whitney_talmud.json.
"""


def esc(s):
    return s.replace('"', '\\"')


def main():
    d = json.load(open(JSON, encoding="utf-8"))
    roots = d["verbal_roots"]
    counts = d["_meta"]["counts"]

    # distinct high-frequency roots for freq-notes
    seen, top = set(), []
    for r in sorted(roots, key=lambda r: (r["dcs_rank"] if r["dcs_rank"] else 10**9,)):
        if r["dcs_rank"] is None:
            break
        if r["root_iast"] in seen:
            continue
        seen.add(r["root_iast"])
        top.append(r)
        if len(top) >= TOP_N:
            break

    props = []
    _nid = [0]

    def next_id():
        _nid[0] += 1
        return f"FN-{_nid[0]:04d}"

    def add(block):
        props.append(block)

    ryad_conf = counts["ryad_confidence"]
    add(
        f'  - id: {next_id()}\n'
        '    target: { appendix: "1", scope: "весь столбец Ряд*" }\n'
        '    type: whitney-ref\n'
        '    proposal: "Столбец «Ряд» в каталоге глагольных корней (Прил. 1) вычислен '
        'алгоритмически из огласовки корня по исчислению Таблицы 2 (Раздел II): '
        'корневой гласный задаёт букву ряда (A/I/U/R/L/M/N), долгота — индекс (₁/₂); '
        'корни на носовой с синкопирующей слабой ступенью отнесены к M/N. '
        f'Из {counts["verbal_roots"]} корней: {ryad_conf.get("high",0)} высокой уверенности, '
        f'{ryad_conf.get("medium",0)} средней, {ryad_conf.get("low",0)} низкой (огласовка уже '
        'в ступени гуна/вриддхи). Прошу утвердить методику как основу каталога — '
        'значения средней/низкой уверенности помечены для ручной проверки."\n'
        '    evidence: "data/whitney_talmud.json → verbal_roots[*].ryad (ryad_source=derived, '
        'ryad_confidence); правило: tools/build_whitney_talmud.py derive_ryad()"\n'
        '    status: pending\n'
        '    approved_by: null'
    )

    set_c = counts["set"]
    add(
        f'  - id: {next_id()}\n'
        '    target: { appendix: "1", scope: "весь столбец seṭ*" }\n'
        '    type: set-correction\n'
        '    proposal: "Столбец «seṭ» выведён ориентировочно по наличию соединительного '
        f'i/ī в причастии p.p.p. (seṭ: {set_c.get("seṭ",0)}, aniṭ: {set_c.get("aniṭ",0)}, '
        f'без данных: {set_c.get("null",0)}). Значение носит вспомогательный характер '
        '(veṭ-корни и супплетивные p.p.p. не различаются) — прошу утвердить как '
        'ориентир, не как нормативную разметку."\n'
        '    evidence: "data/whitney_talmud.json → verbal_roots[*].set (set_source=derived-ppp); '
        'сверка с WhitneyRoots/crosswalk/ppp_validation.json"\n'
        '    status: pending\n'
        '    approved_by: null'
    )

    for r in top:
        cls = "/".join(r["class"]) if r["class"] else "—"
        add(
            f'  - id: {next_id()}\n'
            f'    target: {{ appendix: "1", root: "√{r["root_iast"]}" }}\n'
            '    type: freq-note\n'
            f'    proposal: "√{r["root_iast"]} — DCS-ранг {r["dcs_rank"]} '
            f'(частота {r["dcs_freq"]}), один из самых частотных корней; '
            f'кандидат в первую когорту для самостоятельного изучения (Ряд* {r["ryad"]}, класс {cls})."\n'
            f'    evidence: "WhitneyRoots/crosswalk/roots.csv whitney_no={r["whitney_no"]}; '
            f'dcs_rank={r["dcs_rank"]}, dcs_freq={r["dcs_freq"]}"\n'
            '    status: pending\n'
            '    approved_by: null'
        )

    body = HEADER + "\nproposals:\n" + "\n".join(props) + "\n"
    open(OUT, "w", encoding="utf-8").write(body)
    print(f"wrote {len(props)} proposals to {os.path.relpath(OUT, FOLDER)}")


if __name__ == "__main__":
    main()
